TrabalhoIHC_MarcosFilho/TrabalhoIHC_MarcosFilho/Controllers/BuscarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TrabalhoIHC_MarcosFilho.Controllers
{
    public class BuscarController : Controller
    {
        //
        // GET: Buscar/
        public ActionResult Index()
        {
            return View();
        }
    }
}

TrabalhoIHC_MarcosFilho/TrabalhoIHC_MarcosFilho/Controllers/CadastroCompletoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TrabalhoIHC_MarcosFilho.Controllers
{
    public class CadastroCompletoController : Controller
    {
        // GET: CadastroCompleto
        public ActionResult Index()
        {
            return View();
        }
    }
}

TrabalhoIHC_MarcosFilho/TrabalhoIHC_MarcosFilho/Controllers/CadastroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TrabalhoIHC_MarcosFilho.Controllers
{
    public class CadastroController : Controller
    {
        //
        // GET: Cadastro/
        public ActionResult Index()
        {
            return View();
        }
    }
}

TrabalhoIHC_MarcosFilho/TrabalhoIHC_MarcosFilho/Controllers/CadastrosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TrabalhoIHC_MarcosFilho.Controllers
{
    public class CadastrosController : Controller
    {
        // GET: Cadastros
        public ActionResult Cadastros()
        {
            return View();
        }
    }
}

TrabalhoIHC_MarcosFilho/TrabalhoIHC_MarcosFilho/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TrabalhoIHC_MarcosFilho.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: Home/
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult NovoHome()
        {
            return View();
        }
    }
}

TrabalhoIHC_MarcosFilho/TrabalhoIHC_MarcosFilho/Controllers/ImprimirRelatorioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TrabalhoIHC_MarcosFilho.Controllers
{
    public class ImprimirRelatorioController : Controller
    {
        // GET: ImprimirRelatorio
        public ActionResult Index()
        {
            return View();
        }
    }
}

TrabalhoIHC_MarcosFilho/TrabalhoIHC_MarcosFilho/Controllers/InformacoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TrabalhoIHC_MarcosFilho.Controllers
{
    public class InformacoesController : Controller
    {
        // GET: Informacoes
        public ActionResult Index()
        {
            return View();
        }
    }
}

TrabalhoIHC_MarcosFilho/TrabalhoIHC_MarcosFilho/Controllers/SaidaDeVeiculoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TrabalhoIHC_MarcosFilho.Controllers
{
    public class SaidaDeVeiculoController : Controller
    {
        // GET: SaidaDeVeiculo
        public ActionResult Index()
        {
            return View();
        }
    }
}

TrabalhoIHC_MarcosFilho/TrabalhoIHC_MarcosFilho/Controllers/TipoDeServicoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TrabalhoIHC_MarcosFilho.Controllers
{
    public class TipoDeServicoController : Controller
    {
        // GET: TipoDeServico
        public ActionResult Index()
        {
            return View();
        }
        
    }
}

TrabalhoIHC_MarcosFilho/TrabalhoIHC_MarcosFilho/Views/Buscar/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/shared/_layout.cshtml";
}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="estilo.css">
    <title>SISVEC</title>

</head>
<body>

    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">SISVEC</a>
            </div>
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">Inicio</a></li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Page 1 <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Page 1-1</a></li>
                        <li><a href="#">Page 1-2</a></li>
                        <li><a href="#">Page 1-3</a></li>
                    </ul>
                </li>
                <li><a href="#">Page 2</a></li>
            </ul>
            <form class="navbar-form navbar-left">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search">
                    <div class="input-group-btn">
                        <button class="btn btn-default" type="submit">
                            <i class="glyphicon glyphicon-search"></i>
                        </button>
                    </div>
                </div>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
                <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
            </ul>
        </div>
    </nav>

<div class="row">
    <div class="col-md-6 col-md-offset-5">
        <h2>Buscar</h2>
    </div>
</div>
</body>
</html>

TrabalhoIHC_MarcosFilho/TrabalhoIHC_MarcosFilho/Views/CadastroCompleto/Index.cshtml
@{
    ViewBag.Title = "Cadastro Completo";
    Layout = "~/Views/shared/_layout.cshtml";
}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="estilo.css">
    <title>SISVEC</title>

</head>

<body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <a style="color:#008B00" class="navbar-brand" href="/Home/Sisvec">SISVEC</a>
            </div>
            <ul class="nav navbar-nav">
                <li><a style="color:#FF0000" class="navbar-brand" href="/Home/Inicio">INICIO</a></li>
                <li><a style="color:#BA55D3" href="/CadastroCompleto/Index">CADASTRO MENSAL</a></li>
            </ul>

            <form class="navbar-form navbar-left">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="BUSCAR">
                    <div class="input-group-btn">
                        <button class="btn btn-default" type="submit">
                            <i class="glyphicon glyphicon-search"></i>
                        </button>
                    </div>
                </div>
            </form>           

        </div>
    </nav>

    <div class="row">
        <div class="col-md-6 col-md-offset-5">
            <h2>CADASTRO MENSAL</h2><br />
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-sm-8">

                <h3 class="text-center">DADOS DO CONDUTOR</h3>
                <div class="col-md-5 col-md-offset-3">
                    <label class="sr-only-focusable">Nome Condutor:</label>
                    <input type="text" class="form-control" placeholder="Nome Condutor:" autofocus />
                </div>
                <div class="col-md-5 col-md-offset-3">
                    <label class="sr-only-focusable">CNH:</label>
                    <input type="text" class="form-control" placeholder="CNH:" autofocus />
                </div>
                <div class="col-md-5 col-md-offset-3">
                    <label class="sr-only-focusable">RG:</label>
                    <input type="text" class="form-control" placeholder="RG:" autofocus />
                </div>
                <div class="col-md-5 col-md-offset-3">
                    <label class="sr-only-focusable">CPF:</label>
                    <input type="text" class="form-control" placeholder="CPF:" autofocus />
                </div>
                <div class="col-md-5 col-md-offset-3">
                    <label class="sr-only-focusable">Endereço:</label>
                    <input type="text" class="form-control" placeholder="Endereço:" autofocus />
                </div>
                <div class="col-md-5 col-md-offset-3">
                    <label class="sr-only-focusable">Contato:</label>
                    <input type="text" class="form-control" placeholder="Email ou Telefone:" autofocus />
                </div>
                
            </div>

            <div class="col-sm-4">

                <h3 class="text-center">DADOS DO VEÍCULO</h3>
                <div class="col-md-push-5 col-md-offset-3">
                    <label class="sr-only-focusable">Placa:</label>
                    <input type="text" class="form-control" placeholder="Placa:" autofocus />
                </div>
                <div class="col-md-push-5 col-md-offset-3">
                    <label class="sr-only-focusable">Ano:</label>
                    <input type="text" class="form-control" placeholder="Ano:" autofocus />
                </div>
                <div class="col-md-push-5 col-md-offset-3">
                    <label class="sr-only-focusable">Cor:</label>
                    <input type="text" class="form-control" placeholder="Cor:" autofocus />
                </div>
                <div class="col-md-push-5 col-md-offset-3">
                    <label class="sr-only-focusable">Modelo:</label>
                    <input type="text" class="form-control" placeholder="Modelo:" autofocus />
                </div>               
            </div>
            
        </div>

    </div><br />        
        <div>        
            <div class="btn-group-lg">
                <button class="btn btn-default" type="button" onclick="location.href='@Url.Action("Index","CadastroCompleto")'">SALVAR INFORMAÇÕES</button>
            </div><p></p><br />
            <div class="btn-group-lg">
                <button class="btn btn-default" type="button" onclick="location.href='@Url.Action("Inicio","Home")'">CANCELAR</button>
            </div><P></P><br />

        </div>
    
</body>
<hr>
<footer>
    <center>
        <p>&copy; 2017 - Todos os Direitos Reservados | Desenvolvimento: JMDBI - Versão 1.0</p>
    </center>
</footer>

</html>

TrabalhoIHC_MarcosFilho/TrabalhoIHC_MarcosFilho/Views/Cadastros/Cadastros.cshtml
@{
    ViewBag.Title = "Cadastros";
    Layout = "~/Views/shared/_layout.cshtml";
}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="estilo.css">
    <title>SISVEC</title>

</head>

<body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <a style="color:#008B00" class="navbar-brand" href="/Home/Sisvec">SISVEC</a>
            </div>
            <ul class="nav navbar-nav">
                <li><a style="color:#FF0000" class="navbar-brand" href="/Home/Inicio">INICIO</a></li>
                <li><a style="color:#7CFC00" href="/Cadastro/Index">CADASTROS</a></li>
            </ul>

            <form class="navbar-form navbar-left">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="BUSCAR">
                    <div class="input-group-btn">
                        <button class="btn btn-default" type="submit">
                            <i class="glyphicon glyphicon-search"></i>
                        </button>
                    </div>
                </div>
            </form>


        </div>
    </nav>

    <div class="row">
        <div class="col-md-6 col-md-offset-5">
            <h2>CADASTROS</h2><br />
        </div>
    </div>
    <div class="row">
        <div class="col-md-5 col-md-offset-3">
            <label class="sr-only-focusable">Nome Condutor:</label>
            <input type="text" class="form-control" placeholder="Nome Condutor:" autofocus />
        </div>
        <div class="col-md-5 col-md-offset-3">
            <label class="sr-only-focusable">Placa Veículo:</label>
            <input type="text" class="form-control" placeholder="Placa Veículo:" autofocus />
        </div>
        <div class="col-md-5 col-md-offset-3">
            <label class="sr-only-focusable">Ano Veículo:</label>
            <input type="text" class="form-control" placeholder="Ano Veículo:" autofocus />
        </div>
        <div class="col-md-5 col-md-offset-3">
            <label class="sr-only-focusable">Cor Veículo:</label>
            <input type="text" class="form-control" placeholder="Cor Veículo:" autofocus />
        </div>
        <div class="col-md-5 col-md-offset-3">
            <label class="sr-only-focusable">Modelo Veículo:</label>
            <input type="text" class="form-control" placeholder="Modelo Veículo:" autofocus />
        </div><p></p>
        <div class="col-md-5 col-md-offset-3">
            <label class="sr-only-focusable">Vaga do Veículo:</label>
            <input type="text" class="form-control" placeholder="Vaga do Veículo:" autofocus />
        </div><p></p><br />

        <div class="btn-group-lg">
            <button class="btn btn-default" type="button" onclick="location.href='@Url.Action("Index","Cadastro")'">SALVAR INFORMAÇÕES</button>
        </div><p></p><br />
        <div class="btn-group-lg">
            <button class="btn btn-default" type="button" onclick="location.href='@Url.Action("Inicio","Home")'">CANCELAR</button>
        </div><P></P><br />
        <div class="btn-group-lg">
            <button class="btn btn-default" type="button" onclick="location.href='@Url.Action("Inicio","Home")'">FINALIZAR CADASTRO</button>
        </div><P></P><br />

    </div>
    <hr>
    <footer>
        <center>
            <p>&copy; 2017 - Todos os Direitos Reservados | Desenvolvimento: JMDBI - Versão 1.0</p>
        </center>
    </footer>

</body>
</html>

TrabalhoIHC_MarcosFilho/TrabalhoIHC_MarcosFilho/Views/Home/Index.cshtml
@model TrabalhoIHC_MarcosFilho.Controllers.HomeController
@{
    ViewBag.Title = "Index";
}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="estilo.css">
    <title>SISVEC</title>

</head>

<body>

    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="~/Views/Home/Index.cshtml">SISVEC</a>
            </div>
            <ul class="nav navbar-nav">
                <li class="active"><a href="~/Views/Home/Index.cshtml">Inicio</a></li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Tipo Serviço <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="~/Views/Cadastro/Index.cshtml">Cadastro Mensal</a></li>
                        <li><a href="~/Views/CadastroCompleto/Index.cshtml">Cadastro Diario</a></li>
                        <li><a href="~/Views/SaidaDeVeiculo/Index.cshtml">Sa4ida Veículo</a></li>
                    </ul>
                </li>
                <li><a href="~/Views/CadastroCompleto/Index.cshtml">Cadastro Mensal</a></li>
            </ul>
            <form class="navbar-form navbar-left">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search">
                    <div class="input-group-btn">
                        <button class="btn btn-default" type="submit">
                            <i class="glyphicon glyphicon-search"></i>
                        </button>
                    </div>
                </div>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#"><span class="glyphicon glyphicon-user"></span> Inscrevar-se</a></li>
                <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Entrar</a></li>
            </ul>
        </div>
    </nav>

    <div class="jumbotron text-center">
        <h1>Sistema de Estacionamento Rotativo de Veiculo</h1>
        <p>Aqui seu veiculo esta seguro</p>
    </div>
    <center>
        <h2> As Novas Tecnologia: vantagens e desvantagens </h2>
    </center>
    <div class="container">
        <div class="row">
            <div class="col-sm-4"> 
                <center>
                    <h3>Estacionamento 01</h3>

                    <table border="1">
                        <tr><td>Vaga 01</td> <td></td> <td>Vaga 11</td></tr>
                        <tr><td>Vaga 02</td> <td></td> <td>Vaga 12</td></tr>
                        <tr><td>Vaga 03</td> <td></td> <td>Vaga 13</td></tr>
                        <tr><td>Vaga 04</td> <td></td> <td>Vaga 14</td></tr>
                        <tr><td>Vaga 05</td> <td></td> <td>Vaga 15</td></tr>
                        <tr><td>Vaga 06</td> <td></td> <td>Vaga 16</td></tr>
                        <tr><td>Vaga 07</td> <td></td> <td>Vaga 17</td></tr>
                        <tr><td>Vaga 08</td> <td></td> <td>Vaga 18</td></tr>
                        <tr><td>Vaga 09</td> <td></td> <td>Vaga 19</td></tr>
                        <tr><td>Vaga 10</td> <td></td> <td>Vaga 20</td></tr>
                    </table><br></br>

                </center>

                <h4>Notícias em tempo real</h4><br></br>
                <p>Não se pode esperar que o computador faça tudo sozinho. Ele fornece-nos informações e recursos, cabendo ao professor planear a aplicação dos mesmos na sala de aula. A pressão constante em relação ao uso da informática torna-se cada vez mais evidente em todas as áreas e isso não é diferente na educação. A todo momento os professores sentem que quem não for capaz de usar a informática como instrumento de ensino-aprendizagem está fora do contexto do mercado de trabalho actual. É peremptório mudar este estado de coisas. </p>
                <p>A evolução das tecnologias de informação e da comunicação impõe uma redefinição do espaço de trabalho. Hoje é mais rápido enviar um e-mail do que uma carta por correio. Cada vez menos será o trabalhador a deslocar-se ao trabalho, e cada vez mais será o trabalho que virá até ao trabalhador. Trabalhar a partir de casa parece ser cada vez mais a hipótese acertada numa altura em que a flexibilidade se tornou num dos assuntos na ordem do dia. O mundo assiste hoje à integração e à implementação de novos meios que permitem uma maior rapidez e eficácia na troca de informação.</p>
            
            </div>
            <div class="col-sm-4"> 

                <center>      
                           
                <h3>Estacionamento 02</h3>
                <table border="1">
                    <tr><td>Vaga 01</td> <td></td> <td>Vaga 11</td></tr>
                    <tr><td>Vaga 02</td> <td></td> <td>Vaga 12</td></tr>
                    <tr><td>Vaga 03</td> <td></td> <td>Vaga 13</td></tr>
                    <tr><td>Vaga 04</td> <td></td> <td>Vaga 14</td></tr>
                    <tr><td>Vaga 05</td> <td></td> <td>Vaga 15</td></tr>
                    <tr><td>Vaga 06</td> <td></td> <td>Vaga 16</td></tr>
                    <tr><td>Vaga 07</td> <td></td> <td>Vaga 17</td></tr>
                    <tr><td>Vaga 08</td> <td></td> <td>Vaga 18</td></tr>
                    <tr><td>Vaga 09</td> <td></td> <td>Vaga 19</td></tr>
                    <tr><td>Vaga 10</td> <td></td> <td>Vaga 20</td></tr>
                </table><br></br>

                </center>

                <h4>Notícias em tempo real</h4><br></br>
                <p>O acesso a redes dentro e fora das empresas, a videoconferência em rede local, a utilização partilhada de documentos em tempo real e a redistribuição de chamadas telefónicas são alguns exemplos destas novas tecnologias.</p>
                <p>As novas tecnologias de comunicação trouxeram enormes vantagens aos mais diversos sectores da sociedade. Podemos verificar o quanto ajudou no processo de recuperação da informação através das bases bibliográficas em CD-ROM e on-line, como também na obtenção do próprio conteúdo desejado. Os periódicos electrónicos retratam uma parcela desse avanço tecnológico, apresentando vantagens e desvantagens tanto na sua forma “física” como nas bases que os disponibilizam. O objectivo desta apresentação é relatar as nossas experiências e considerações sobre essa nova modalidade de publicação.</p>
                
            </div>
            <div class="col-sm-4">

                <center>

                <h3>Estacionamento 03</h3>
                <table border="1">
                    <tr><td>Vaga 01</td> <td></td> <td>Vaga 11</td></tr>
                    <tr><td>Vaga 02</td> <td></td> <td>Vaga 12</td></tr>
                    <tr><td>Vaga 03</td> <td></td> <td>Vaga 13</td></tr>
                    <tr><td>Vaga 04</td> <td></td> <td>Vaga 14</td></tr>
                    <tr><td>Vaga 05</td> <td></td> <td>Vaga 15</td></tr>
                    <tr><td>Vaga 06</td> <td></td> <td>Vaga 16</td></tr>
                    <tr><td>Vaga 07</td> <td></td> <td>Vaga 17</td></tr>
                    <tr><td>Vaga 08</td> <td></td> <td>Vaga 18</td></tr>
                    <tr><td>Vaga 09</td> <td></td> <td>Vaga 19</td></tr>
                    <tr><td>Vaga 10</td> <td></td> <td>Vaga 20</td></tr>
                </table><br></br>

                </center>

                <h4>Notícias em tempo real</h4><br></br>
                <p>Hoje existem diversos “sites” na Internet que disponibilizam periódicos electrónicos. Neste cenário, encontramos uma grande variedade de interfaces, que, por vezes, comprometem os resultados das pesquisas, uma vez que as dificuldades encontradas pelos usuários para realizar uma pesquisa bibliográfica são elementos desenregelantes e geradores de buscas ineficientes ou mesmo incorrectas. É compreensível que vários factores concorram para que haja tamanha diversidade e mesmo mudança de interface nos sites de busca bibliográfica, pois nessa era globalizada em que estamos inseridos, tudo parece mudar muito rapidamente. A própria Internet aparece como factor desencadeante principal de tantas mudanças, onde se percebe quase que uma “anarquia controlada”. Os sites acompanham as tendências tanto de design como de objectivos específicos.</p>
                <p>UÉ preciso que os profissionais da informação estejam atentos às constantes mudanças que se operam neste campo em constante actualização.</p>
                
            </div>
        </div>

    </div>
</body>
</html>

TrabalhoIHC_MarcosFilho/TrabalhoIHC_MarcosFilho/Views/TipoDeServico/Index.cshtml
@{
    ViewBag.Title = "Tipo de Serviço";
}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="estilo.css">
    <title>SISVEC</title>
    <style>
        .modal footer {
            text-align: center;
            padding: 0 !important;
        }

        .modal:before {
            content: '';
            display: inline-block;
            height: 100%;
            vertical-align: middle;
            margin-right: -4px;
        }

        .modal-dialog {
            display: inline-block;
            text-align: left;
            vertical-align: middle;
        }
    </style>

</head>

<body>
    <div>

        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a style="color:#008B00" class="navbar-brand" href="/Home/Sisvec">SISVEC</a>
                </div>
                <ul class="nav navbar-nav">
                    <li><a style="color:#FF0000" class="navbar-brand" href="/Home/Inicio">INICIO</a></li>
                    <li><a style="color:#FFFF00" href="/TipoDeServico/Index">TIPO SERVIÇO</a></li>
                </ul>

                <form class="navbar-form navbar-left">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="BUSCAR">
                        <div class="input-group-btn">
                            <button class="btn btn-default" type="submit">
                                <i class="glyphicon glyphicon-search"></i>
                            </button>
                        </div>
                    </div>
                </form>

            </div>
        </nav>
    </div>

    <h2 class="text-center">TIPO DE SERVIÇO</h2><br />

    <div class="btn-group-lg">
        <button class="btn btn-default" type="button" onclick="location.href='@Url.Action("Index","Cadastro")'">DIÁRIO</button>
    </div><p></p><br />
    <div class="btn-group-lg">
        <button class="btn btn-default" type="button" onclick="location.href='@Url.Action("Index","CadastroCompleto")'">MENSAL</button>
    </div><P></P><br />
    <div class="btn-group-lg">
        <button class="btn btn-default" type="button" onclick="location.href='@Url.Action("Index","SaidaDeVeiculo")'">SAÍDA DE VEÍCULO</button>
    </div><p></p><br />
    <div class="btn-group-lg">
        <button class="btn btn-default" type="button" onclick="location.href='@Url.Action("Index","ImprimirRelatorio")'">IMPRIMIR RELATÓRIO</button>
    </div><p></p><br />
    
    <div>
        <hr>
        <footer>
            <center>
                <p>&copy; 2017 - Todos os Direitos Reservados | Desenvolvimento: JMDBI - Versão 1.0</p>
            </center>
        </footer>
        </hr>
    </div>
</body>
</html>